/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 untitled.glb satelit
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Satelit(props) {
  const { nodes, materials } = useGLTF('/untitled.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={[1, 0.58, 1]} position={[-3.07, -0.71, 0.4]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials.Материал} />
        <mesh geometry={nodes.Cube_3.geometry} material={materials['Материал.002']} />
        <mesh geometry={nodes.Cube_4.geometry} material={materials['Материал.003']} />
        <mesh geometry={nodes.Cube_5.geometry} material={materials['Материал.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/untitled.glb')
